/*
 * Copyright (C) 2021, Kasem S.M
 * All rights reserved.
 */
package kasem.sm.slime.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0158ca)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd8e2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001947)
val md_theme_light_secondary = Color(0xFF575e72)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdce2f9)
val md_theme_light_onSecondaryContainer = Color(0xFF141b2c)
val md_theme_light_tertiary = Color(0xFF725572)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFfdd7fa)
val md_theme_light_onTertiaryContainer = Color(0xFF2a132c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfbff)
val md_theme_light_onBackground = Color(0xFF1b1b1e)
val md_theme_light_surface = Color(0xFFfdfbff)
val md_theme_light_onSurface = Color(0xFF1b1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe1e2ec)
val md_theme_light_onSurfaceVariant = Color(0xFF44464e)
val md_theme_light_outline = Color(0xFF757780)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0f4)
val md_theme_light_inverseSurface = Color(0xFF303033)

val md_theme_dark_primary = Color(0xFFafc6ff)
val md_theme_dark_onPrimary = Color(0xFF002c71)
val md_theme_dark_primaryContainer = Color(0xFF00419f)
val md_theme_dark_onPrimaryContainer = Color(0xFFd8e2ff)
val md_theme_dark_secondary = Color(0xFFc0c6dc)
val md_theme_dark_onSecondary = Color(0xFF293042)
val md_theme_dark_secondaryContainer = Color(0xFF404659)
val md_theme_dark_onSecondaryContainer = Color(0xFFdce2f9)
val md_theme_dark_tertiary = Color(0xFFe0bbde)
val md_theme_dark_onTertiary = Color(0xFF412842)
val md_theme_dark_tertiaryContainer = Color(0xFF593d5a)
val md_theme_dark_onTertiaryContainer = Color(0xFFfdd7fa)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1e)
val md_theme_dark_onBackground = Color(0xFFe4e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1e)
val md_theme_dark_onSurface = Color(0xFFe4e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF44464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc5c6d0)
val md_theme_dark_outline = Color(0xFF8e9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe4e2e6)
