name: Slime Build (Android)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Permission for Gradle Execution
        run: chmod +x gradlew

      - name: Slime Code Review
        run: ./gradlew spotlessCheck