name: Slime Android Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Permission for Gradle Execution
        run: chmod +x gradlew

      - name: Slime Unit Tests Check
        run: ./gradlew test
